# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
on:
  push:
  pull_request:

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: windows-latest, r: 'release'}
          - {os: macOS-latest, r: 'release'}
          - {os: ubuntu-latest, r: 'release'}
          - {os: ubuntu-latest, r: 'devel', http-user-agent: 'release'}
          - {os: ubuntu-latest, r: 'oldrel-1'}
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
    steps:
        - name: Checking out the repository
          uses: actions/checkout@v4

        - name: Setting up pandoc
          uses: r-lib/actions/setup-pandoc@v2

        - name: Setting up R ${{ matrix.config.r }} on ${{ matrix.config.os }}
          uses: r-lib/actions/setup-r@v2
          with:
            r-version: ${{ matrix.config.r }}
            http-user-agent: ${{ matrix.config.http-user-agent }}
            use-public-rspm: true

        - name: Querying dependencies
          uses: r-lib/actions/setup-r-dependencies@v2
          with:
            extra-packages: any::rcmdcheck
            needs: check

        - name: Checking package
          uses: r-lib/actions/check-r-package@v2
          with:
            args: 'c("--no-manual", "--as-cran")'
            error-on: '"error"'
            check-dir: '"check"'
            upload-snapshots: true